In [1]:
##Question 1

In [2]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [3]:
##Question 2

In [5]:
m=[]
n=[]
for i in range(5):
    x=int(input("\nEnter the value for m : "))
    m.append(x)
print("\n m List Values are:",m)
for i in range(5):
    x=int(input("\nEnter the value for n : "))
    n.append(x)
print("\n n List Values are:",n)
a=np.array(m)
b=np.array(n)
c=np.concatenate((a,b))
print("\n Concatenated Array is :",c)
np.sort(c)
print("\n Sorted Array is :",np.sort(c))


Enter the value for m : 40

Enter the value for m : 25

Enter the value for m : 30

Enter the value for m : 10

Enter the value for m : 5

 m List Values are: [40, 25, 30, 10, 5]

Enter the value for n : 15

Enter the value for n : 45

Enter the value for n : 100

Enter the value for n : 250

Enter the value for n : 50

 n List Values are: [15, 45, 100, 250, 50]

 Concatenated Array is : [ 40  25  30  10   5  15  45 100 250  50]

 Sorted Array is : [  5  10  15  25  30  40  45  50 100 250]


In [23]:
##Question 3

In [24]:
a = np.array([[1,2,3],[1,3,5],[12,15,25]])
print("\nDimensions in array : ", arr.ndim)
print("\nSize of array : ", arr.size)


Dimensions in array :  2

Size of array :  9


In [ ]:
## Question 4
##a)np.newaxis

In [28]:
b = np.arange(25)
print("\n Shape of Array :",b.shape)
row_b = b[np.newaxis, :]
print("\n Shape of 2D Array in row major :",row_b.shape)
col_b = b[:, np.newaxis]
print("\n Shape of 2D Array in column major :",col_b.shape)


 Shape of Array : (25,)

 Shape of 2D Array in row major : (1, 25)

 Shape of 2D Array in column major : (25, 1)


In [29]:
##b)np.expand_dims

In [30]:
z = np.arange(25)
print("\n Shape of Array :",z.shape)
row_z = np.expand_dims(z, axis=0)
print("\n Shape of 2D Array in row major :",row_z.shape)
col_z = np.expand_dims(z, axis=1)
print("\n Shape of 2D Array in column major :",col_z.shape)



 Shape of Array : (25,)

 Shape of 2D Array in row major : (1, 25)

 Shape of 2D Array in column major : (25, 1)


In [31]:
## Question 5
##a) np.vstack

In [33]:
a=[10,20,30]
b=[50,60,80]
np.vstack((a,b))

array([[10, 20, 30],
       [50, 60, 80]])

In [35]:
##b)np.hstack

In [36]:
np.hstack((a,b))

array([10, 20, 30, 50, 60, 80])

In [37]:
## Question 6

In [41]:
a = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10,100,1000])
np.unique(a,return_counts=True)
np.asarray(np.unique(a,return_counts=True))

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   16,
          25,  100, 1000],
       [   2,    2,    1,    2,    2,    1,    1,    1,    1,    1,    1,
           1,    1,    1]], dtype=int64)